FROM redhat/ubi8:latest

### Install OpenJDK ###

ARG JAVA_VERSION=1.8.0
RUN yum install -y java-${JAVA_VERSION}-openjdk \
                   java-${JAVA_VERSION}-openjdk-devel
ENV JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-openjdk/

### Install Git ###

RUN yum install -y git

### Install SBT ###

RUN curl -o /etc/yum.repos.d/sbt-rpm.repo https://www.scala-sbt.org/sbt-rpm.repo && \
    yum install -y sbt

### Setting group/user ###

ARG USERID=1000
ARG GROUPID=1000

RUN groupadd --gid ${GROUPID} developers && \
    useradd -G wheel --uid ${USERID} --gid ${GROUPID} developer && \
    mkdir -p /epfl-scala-specialization && \
    chown -R ${GROUPID}:${USERID} /epfl-scala-specialization

USER developer
